name: Docker Compose CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Free up storage
      run: |
        # Remove preinstalled tool cache
        sudo rm -rf /opt/hostedtoolcache

        # Clear APT cache
        sudo apt-get clean
        sudo rm -rf /var/lib/apt/lists/*

        # Remove unused Docker resources
        docker system prune -af --volumes

        # Clear specific caches (if applicable)
        rm -rf ~/.npm ~/.cache/pip

        # Print available disk space for debugging
        df -h

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build containers
      run: |
        docker compose -f docker-compose.yml build
